spring:
    application:
        name: carrieroperator
    datasource:
        druid:
            username: root
            password: 123456
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/carrierdata?characterEncoding=utf8&&useSSL=true
        logging:
            level: trace
mybatis:
    type-aliases-package:
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30





